In [51]:
from sklearn.datasets import load_wine
import pandas as pd
from pycaret.classification import *

In [52]:
 data = load_wine(as_frame=True)

In [69]:
df = data.data

In [70]:
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

In [71]:
label = data.target
print(label.value_counts())

d = {'quality':label}
label = pd.DataFrame(d)
label.head()

1    71
0    59
2    48
Name: target, dtype: int64

   quality
0        0
1        0
2        0
3        0
4        0

In [73]:
dataset = pd.concat([df,label],axis=1)
dataset.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,quality
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

In [74]:
dataset.drop(['proline','od280/od315_of_diluted_wines'],inplace=True,axis=1)
dataset.shape

(178, 12)

In [75]:
model_classify = setup(dataset,'quality',session_id=45)

In [76]:
%%time
best = compare_models()

Wall time: 11.7 s

In [77]:
et_model = create_model('et')

In [78]:
evaluate_model(et_model)

                         Parameters
bootstrap                     False
ccp_alpha                       0.0
class_weight                   None
criterion                      gini
max_depth                      None
max_features                   auto
max_leaf_nodes                 None
max_samples                    None
min_impurity_decrease           0.0
min_impurity_split             None
min_samples_leaf                  1
min_samples_split                 2
min_weight_fraction_leaf        0.0
n_estimators                    100
n_jobs                           -1
oob_score                     False
random_state                     45
verbose                           0
warm_start                    False

In [79]:
predict_model(et_model)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,quality,Label,Score
0,13.23,3.30,2.28,18.500000,98.0,1.80,0.83,0.61,1.87,10.52,0.56,2,2,0.83
1,13.69,3.26,2.54,20.000000,107.0,1.83,0.56,0.50,0.80,5.88,0.96,2,2,0.92
2,14.23,1.71,2.43,15.600000,127.0,2.80,3.06,0.28,2.29,5.64,1.04,0,0,1.00
3,12.17,1.45,2.53,19.000000,104.0,1.89,1.75,0.45,1.03,2.95,1.45,1,1,0.92
4,13.67,1.25,1.92,18.000000,94.0,2.10,1.79,0.32,0.73,3.80,1.23,1,1,0.62
5,12.21,1.19,1.75,16.799999,151.0,1.85,1.28,0.14,2.50,2.85,1.28,1,1,0.95
6,14.13,4.10,2.74,24.500000,96.0,2.05,0.76,0.56,1.35,9.20,0.61,2,2,0.96
7,14.37,1.95,2.50,16.799999,113.0,3.85,3.49,0.24,2.18,7.80,0.86,0,0,0.97
8,14.10,2.16,2.30,18.000000,105.0,2.95,3.32,0.22,2.38,5.75,1.25,0,0,0.97
9,12.08,1.13,2.51,24.000000,78.0,2.00,1.58,0.40,1.40,2.20,1.31,1,1,0.97
10,11.41,0.74,2.50,21.000000,88.0,2.48,2.01,0.42,1.44,3.08,1.10,1,1,0.94
11,13.48,1.81,2.41,20.500000,100.0,2.70,2.98,0.26,1.86,5.10,1.04,0,0,0.88
12,13.07,1.50,2.10,15.500000,98.0,2.40,2.64,0.28,1.37,3.70,1.18,0,0,0.65
13,12.36,3.83,2.38,21.000000,88.0,2.30,0.92,0.50,1.04,7.65,0.56,2,2,0.82
14,12.00,1.51,2.42,22.000000,86.0,1.45,1.25,0.50,1.63,3.60,1.05,1,1,0.87
15,12.08,1.83,2.32,18.500000,81.0,1.60,1.50,0.52,1.64,2.40,1.08,1,1,0.98
16,12.29,3.17,2.21,18.000000,88.0,2.85,2.99,0.45,2.81,2.30,1.42,1,1,0.87
17,12.64,1.36,2.02,16.799999,100.0,2.02,1.41,0.53,0.62,5.75,0.98,1,1,0.54
18,13.08,3.90,2.36,21.500000,113.0,1.41,1.39,0.34,1.14,9.40,0.57,2,2,0.88
19,13.73,4.36,2.26,22.500000,88.0,1.28,0.47,0.52,1.15,6.62,0.78,2,2,0.91
20,11.61,1.35,2.70,20.000000,94.0,2.74,2.92,0.29,2.49,2.65,0.96,1,1,0.84
21,13.50,3.12,2.62,24.000000,123.0,1.40,1.57,0.22,1.25,8.60,0.59,2,2,0.82
22,14.02,1.68,2.21,16.000000,96.0,2.65,2.33,0.26,1.98,4.70,1.04,0,0,0.96
23,12.51,1.24,2.25,17.500000,85.0,2.00,0.58,0.60,1.25,5.45,0.75,2,2,0.55
24,12.79,2.67,2.48,22.000000,112.0,1.48,1.36,0.24,1.26,10.80,0.48,2,2,0.92
25,12.45,3.03,2.64,27.000000,97.0,1.90,0.58,0.63,1.14,7.50,0.67,2,2,0.92
26,13.87,1.90,2.80,19.400000,107.0,2.95,2.97,0.37,1.76,4.50,1.25,0,0,0.88
27,13.03,0.90,1.71,16.000000,86.0,1.95,2.03,0.24,1.46,4.60,1.19,1,1,0.66
28,12.82,3.37,2.30,19.500000,88.0,1.48,0.66,0.40,0.97,10.26,0.72,2,2,0.96
29,12.58,1.29,2.10,20.000000,103.0,1.48,0.58,0.53,1.40,7.60,0.58,2,2,0.76
30,13.17,5.19,2.32,22.000000,93.0,1.74,0.63,0.61,1.55,7.90,0.60,2,2,0.92
31,13.58,2.58,2.69,24.500000,105.0,1.55,0.84,0.39,1.54,8.66,0.74,2,2,0.90
32,13.45,3.70,2.60,23.000000,111.0,1.70,0.92,0.43,1.46,10.68,0.85,2,2,0.85
33,13.72,1.43,2.50,16.700001,108.0,3.40,3.67,0.19,2.04,6.80,0.89,0,0,0.95
34,12.42,1.61,2.19,22.500000,108.0,2.00,2.09,0.34,1.61,2.06,1.06,1,1,0.94
35,12.25,3.88,2.20,18.500000,112.0,1.38,0.78,0.29,1.14,8.21,0.65,2,2,0.93
36,13.51,1.80,2.65,19.000000,110.0,2.35,2.53,0.29,1.54,4.20,1.10,0,0,0.87
37,13.56,1.71,2.31,16.200001,117.0,3.15,3.29,0.34,2.34,6.13,0.95,0,0,0.94
38,13.24,2.59,2.87,21.000000,118.0,2.80,2.69,0.39,1.82,4.32,1.04,0,0,0.74
39,14.21,4.04,2.44,18.900000,111.0,2.85,2.65,0.30,1.25,5.24,0.87,0,0,0.90
40,11.76,2.68,2.92,20.000000,103.0,1.75,2.03,0.60,1.05,3.80,1.23,1,1,0.77
41,11.79,2.13,2.78,28.500000,92.0,2.13,2.24,0.58,1.76,3.00,0.97,1,1,0.90
42,12.08,1.33,2.30,23.600000,70.0,2.20,1.59,0.42,1.38,1.74,1.07,1,1,0.97
43,12.00,3.43,2.00,19.000000,87.0,2.00,1.64,0.37,1.87,1.28,0.93,1,1,0.99
44,12.67,0.98,2.24,18.000000,99.0,2.20,1.94,0.30,1.46,2.62,1.23,1,1,0.91
45,13.84,4.12,2.38,19.500000,89.0,1.80,0.83,0.48,1.56,9.01,0.57,2,2,0.94
46,12.85,3.27,2.58,22.000000,106.0,1.65,0.60,0.60,0.96,5.58,0.87,2,2,0.92
47,12.81,2.31,2.40,24.000000,98.0,1.15,1.09,0.27,0.83,5.70,0.66,2,2,0.87
48,13.05,2.05,3.22,25.000000,124.0,2.63,2.68,0.47,1.92,3.58,1.13,0,1,0.51
49,13.11,1.01,1.70,15.000000,78.0,2.98,3.18,0.26,2.28,5.30,1.12,1,0,0.53
50,14.75,1.73,2.39,11.400000,91.0,3.10,3.69,0.43,2.81,5.40,1.25,0,0,0.91
51,13.39,1.77,2.62,16.100000,93.0,2.85,2.94,0.34,1.45,4.80,0.92,0,0,0.88
52,13.48,1.67,2.64,22.500000,89.0,2.60,1.10,0.52,2.29,11.75,0.57,2,2,0.66
53,13.05,1.77,2.10,17.000000,107.0,3.00,3.00,0.28,2.03,5.04,0.88,0,0,0.81

In [80]:
save_model(et_model, model_name = 'extra_tree_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=[],
                                       ml_usecase='classification',
                                       numerical_features=[], target='quality',
                                       time_features=[])),
                 ('imputer',
                  Simple_Imputer(categorical_strategy='not_available',
                                 fill_value_categorical=None,
                                 fill_value_numerical=None,
                                 numeric_stra...
                  ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0,
                                       class_weight=None, criterion='gini',
                                       max_depth=None, max_features='auto',
                                       max_leaf_nodes=None, max_samples=None,
                                       min_impurity_decrease=0.0,
                                       min_impurity_split=None,
                                       min_samples_leaf=1, min_samples_split=2,
                                       min_weight_fraction_leaf=0.0,
                                       n_estimators=100, n_jobs=-1,
                                       oob_score=False, random_state=45,
                                       verbose=0, warm_start=False)]],
          verbose=False),
 'extra_tree_model.pkl')

In [83]:
dataset.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,quality
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,0.938202
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.775035
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,0.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,0.000000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,1.000000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,2.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,2.000000